# Generated by Django 2.2.5 on 2019-09-04 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('card_details', models.CharField(max_length=150)),
                ('card_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_added', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_deducted', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash',
                'verbose_name_plural': 'Cashes',
                'ordering': ['-date'],
            },
        ),
    ]
