# Generated by Django 2.2.5 on 2019-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20190905_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
