# Generated by Django 2.2.5 on 2019-09-11 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0004_auto_20190906_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('card_type', models.CharField(blank=True, choices=[('----', '----'), ('Debit', 'Debit'), ('Credit', 'Credit')], default=0, max_length=150, null=True)),
                ('card_number', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance per user',
                'verbose_name_plural': 'Balance per users',
                'ordering': ['-date_added'],
            },
        ),
    ]
