# Generated by Django 2.2.5 on 2019-09-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='wallet_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.Wallet'),
        ),
    ]
