# Generated by Django 2.2.5 on 2019-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_cash_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
