# Generated by Django 2.2.5 on 2019-09-14 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cash',
            name='wallet_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
    ]
